services:
  site:
    image: giselerezende/mkts-gisele:site
    ports:
      - "3333:3333"
    networks:
      - mkts-network
    depends_on:
      - db
  db:
    image: giselerezende/mkts-gisele:db
    ports:
      - "3306:3306"
    networks:
      - mkts-network
networks:
  mkts-network:
    driver: bridge
